=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::BankApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BankApi' do
  before do
    # run before each test
    @instance = SwaggerClient::BankApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BankApi' do
    it 'should create an instance of BankApi' do
      expect(@instance).to be_instance_of(SwaggerClient::BankApi)
    end
  end

  # unit tests for bank_accounts_address_transfers_post
  # Send coins from one account to another
  # @param address Account address in bech32 format
  # @param account The sender and tx information
  # @param [Hash] opts the optional parameters
  # @return [StdTx]
  describe 'bank_accounts_address_transfers_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for bank_balances_address_get
  # Get the account balances
  # @param address Account address in bech32 format
  # @param [Hash] opts the optional parameters
  # @return [Array<Coin>]
  describe 'bank_balances_address_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
