=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MintApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MintApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MintApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MintApi' do
    it 'should create an instance of MintApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MintApi)
    end
  end

  # unit tests for minting_annual_provisions_get
  # Current minting annual provisions value
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'minting_annual_provisions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for minting_inflation_get
  # Current minting inflation value
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'minting_inflation_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for minting_parameters_get
  # Minting module parameters
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'minting_parameters_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
