=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SecretRESTApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SecretRESTApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SecretRESTApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SecretRESTApi' do
    it 'should create an instance of SecretRESTApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SecretRESTApi)
    end
  end

  # unit tests for node_info_get
  # The properties of the connected node
  # Information about the connected node
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'node_info_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
