=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SlashingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SlashingApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SlashingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SlashingApi' do
    it 'should create an instance of SlashingApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SlashingApi)
    end
  end

  # unit tests for slashing_parameters_get
  # Get the current slashing parameters
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2007]
  describe 'slashing_parameters_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for slashing_signing_infos_get
  # Get sign info of given all validators
  # Get sign info of all validators
  # @param page Page number
  # @param limit Maximum number of items per page
  # @param [Hash] opts the optional parameters
  # @return [Array<SigningInfo>]
  describe 'slashing_signing_infos_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for slashing_validators_validator_addr_unjail_post
  # Unjail a jailed validator
  # Send transaction to unjail a jailed validator
  # @param validator_addr Bech32 validator address
  # @param unjail_body 
  # @param [Hash] opts the optional parameters
  # @return [StdTx]
  describe 'slashing_validators_validator_addr_unjail_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
