=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::SupplyApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SupplyApi' do
  before do
    # run before each test
    @instance = SwaggerClient::SupplyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupplyApi' do
    it 'should create an instance of SupplyApi' do
      expect(@instance).to be_instance_of(SwaggerClient::SupplyApi)
    end
  end

  # unit tests for supply_total_denomination_get
  # Total supply of a single coin denomination
  # @param denomination Coin denomination
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'supply_total_denomination_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for supply_total_get
  # Total supply of coins in the chain
  # @param [Hash] opts the optional parameters
  # @return [Supply]
  describe 'supply_total_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
