=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::TendermintRPCApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TendermintRPCApi' do
  before do
    # run before each test
    @instance = SwaggerClient::TendermintRPCApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TendermintRPCApi' do
    it 'should create an instance of TendermintRPCApi' do
      expect(@instance).to be_instance_of(SwaggerClient::TendermintRPCApi)
    end
  end

  # unit tests for blocks_height_get
  # Get a block at a certain height
  # @param height Block height
  # @param [Hash] opts the optional parameters
  # @return [BlockQuery]
  describe 'blocks_height_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for blocks_latest_get
  # Get the latest block
  # @param [Hash] opts the optional parameters
  # @return [BlockQuery]
  describe 'blocks_latest_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for syncing_get
  # Syncing state of node
  # Get if the node is currently syning with other nodes
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'syncing_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for validatorsets_height_get
  # Get a validator set a certain height
  # @param height Block height
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'validatorsets_height_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for validatorsets_latest_get
  # Get the latest validator set
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2002]
  describe 'validatorsets_latest_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
