=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::BlockQueryBlockMeta
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BlockQueryBlockMeta' do
  before do
    # run before each test
    @instance = SwaggerClient::BlockQueryBlockMeta.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BlockQueryBlockMeta' do
    it 'should create an instance of BlockQueryBlockMeta' do
      expect(@instance).to be_instance_of(SwaggerClient::BlockQueryBlockMeta)
    end
  end
  describe 'test attribute "header"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "block_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
