=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::DuplicateVoteEvidence
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DuplicateVoteEvidence' do
  before do
    # run before each test
    @instance = SwaggerClient::DuplicateVoteEvidence.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DuplicateVoteEvidence' do
    it 'should create an instance of DuplicateVoteEvidence' do
      expect(@instance).to be_instance_of(SwaggerClient::DuplicateVoteEvidence)
    end
  end
end
