=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::InlineResponse2008
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse2008' do
  before do
    # run before each test
    @instance = SwaggerClient::InlineResponse2008.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse2008' do
    it 'should create an instance of InlineResponse2008' do
      expect(@instance).to be_instance_of(SwaggerClient::InlineResponse2008)
    end
  end
  describe 'test attribute "min_deposit"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "max_deposit_period"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
