=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'date'

module SwaggerClient
  class InlineResponse2007
    attr_accessor :max_evidence_age

    attr_accessor :signed_blocks_window

    attr_accessor :min_signed_per_window

    attr_accessor :double_sign_unbond_duration

    attr_accessor :downtime_unbond_duration

    attr_accessor :slash_fraction_double_sign

    attr_accessor :slash_fraction_downtime

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'max_evidence_age' => :'max_evidence_age',
        :'signed_blocks_window' => :'signed_blocks_window',
        :'min_signed_per_window' => :'min_signed_per_window',
        :'double_sign_unbond_duration' => :'double_sign_unbond_duration',
        :'downtime_unbond_duration' => :'downtime_unbond_duration',
        :'slash_fraction_double_sign' => :'slash_fraction_double_sign',
        :'slash_fraction_downtime' => :'slash_fraction_downtime'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'max_evidence_age' => :'String',
        :'signed_blocks_window' => :'String',
        :'min_signed_per_window' => :'String',
        :'double_sign_unbond_duration' => :'String',
        :'downtime_unbond_duration' => :'String',
        :'slash_fraction_double_sign' => :'String',
        :'slash_fraction_downtime' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'max_evidence_age')
        self.max_evidence_age = attributes[:'max_evidence_age']
      end

      if attributes.has_key?(:'signed_blocks_window')
        self.signed_blocks_window = attributes[:'signed_blocks_window']
      end

      if attributes.has_key?(:'min_signed_per_window')
        self.min_signed_per_window = attributes[:'min_signed_per_window']
      end

      if attributes.has_key?(:'double_sign_unbond_duration')
        self.double_sign_unbond_duration = attributes[:'double_sign_unbond_duration']
      end

      if attributes.has_key?(:'downtime_unbond_duration')
        self.downtime_unbond_duration = attributes[:'downtime_unbond_duration']
      end

      if attributes.has_key?(:'slash_fraction_double_sign')
        self.slash_fraction_double_sign = attributes[:'slash_fraction_double_sign']
      end

      if attributes.has_key?(:'slash_fraction_downtime')
        self.slash_fraction_downtime = attributes[:'slash_fraction_downtime']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          max_evidence_age == o.max_evidence_age &&
          signed_blocks_window == o.signed_blocks_window &&
          min_signed_per_window == o.min_signed_per_window &&
          double_sign_unbond_duration == o.double_sign_unbond_duration &&
          downtime_unbond_duration == o.downtime_unbond_duration &&
          slash_fraction_double_sign == o.slash_fraction_double_sign &&
          slash_fraction_downtime == o.slash_fraction_downtime
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [max_evidence_age, signed_blocks_window, min_signed_per_window, double_sign_unbond_duration, downtime_unbond_duration, slash_fraction_double_sign, slash_fraction_downtime].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
