=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'date'

module SwaggerClient
  class InlineResponse2006
    attr_accessor :inflation_rate_change

    attr_accessor :inflation_max

    attr_accessor :inflation_min

    attr_accessor :goal_bonded

    attr_accessor :unbonding_time

    attr_accessor :max_validators

    attr_accessor :bond_denom

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'inflation_rate_change' => :'inflation_rate_change',
        :'inflation_max' => :'inflation_max',
        :'inflation_min' => :'inflation_min',
        :'goal_bonded' => :'goal_bonded',
        :'unbonding_time' => :'unbonding_time',
        :'max_validators' => :'max_validators',
        :'bond_denom' => :'bond_denom'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'inflation_rate_change' => :'String',
        :'inflation_max' => :'String',
        :'inflation_min' => :'String',
        :'goal_bonded' => :'String',
        :'unbonding_time' => :'String',
        :'max_validators' => :'Integer',
        :'bond_denom' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'inflation_rate_change')
        self.inflation_rate_change = attributes[:'inflation_rate_change']
      end

      if attributes.has_key?(:'inflation_max')
        self.inflation_max = attributes[:'inflation_max']
      end

      if attributes.has_key?(:'inflation_min')
        self.inflation_min = attributes[:'inflation_min']
      end

      if attributes.has_key?(:'goal_bonded')
        self.goal_bonded = attributes[:'goal_bonded']
      end

      if attributes.has_key?(:'unbonding_time')
        self.unbonding_time = attributes[:'unbonding_time']
      end

      if attributes.has_key?(:'max_validators')
        self.max_validators = attributes[:'max_validators']
      end

      if attributes.has_key?(:'bond_denom')
        self.bond_denom = attributes[:'bond_denom']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          inflation_rate_change == o.inflation_rate_change &&
          inflation_max == o.inflation_max &&
          inflation_min == o.inflation_min &&
          goal_bonded == o.goal_bonded &&
          unbonding_time == o.unbonding_time &&
          max_validators == o.max_validators &&
          bond_denom == o.bond_denom
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [inflation_rate_change, inflation_max, inflation_min, goal_bonded, unbonding_time, max_validators, bond_denom].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
