=begin
#Testnet Secret API for Secret Network

#A REST interface for state queries, transaction generation and broadcasting.

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'uri'

module SwaggerClient
  class TendermintRPCApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get a block at a certain height
    # @param height Block height
    # @param [Hash] opts the optional parameters
    # @return [BlockQuery]
    def blocks_height_get(height, opts = {})
      data, _status_code, _headers = blocks_height_get_with_http_info(height, opts)
      data
    end

    # Get a block at a certain height
    # @param height Block height
    # @param [Hash] opts the optional parameters
    # @return [Array<(BlockQuery, Fixnum, Hash)>] BlockQuery data, response status code and response headers
    def blocks_height_get_with_http_info(height, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TendermintRPCApi.blocks_height_get ...'
      end
      # verify the required parameter 'height' is set
      if @api_client.config.client_side_validation && height.nil?
        fail ArgumentError, "Missing the required parameter 'height' when calling TendermintRPCApi.blocks_height_get"
      end
      # resource path
      local_var_path = '/blocks/{height}'.sub('{' + 'height' + '}', height.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'BlockQuery')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TendermintRPCApi#blocks_height_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get the latest block
    # @param [Hash] opts the optional parameters
    # @return [BlockQuery]
    def blocks_latest_get(opts = {})
      data, _status_code, _headers = blocks_latest_get_with_http_info(opts)
      data
    end

    # Get the latest block
    # @param [Hash] opts the optional parameters
    # @return [Array<(BlockQuery, Fixnum, Hash)>] BlockQuery data, response status code and response headers
    def blocks_latest_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TendermintRPCApi.blocks_latest_get ...'
      end
      # resource path
      local_var_path = '/blocks/latest'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'BlockQuery')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TendermintRPCApi#blocks_latest_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Syncing state of node
    # Get if the node is currently syning with other nodes
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse2001]
    def syncing_get(opts = {})
      data, _status_code, _headers = syncing_get_with_http_info(opts)
      data
    end

    # Syncing state of node
    # Get if the node is currently syning with other nodes
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse2001, Fixnum, Hash)>] InlineResponse2001 data, response status code and response headers
    def syncing_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TendermintRPCApi.syncing_get ...'
      end
      # resource path
      local_var_path = '/syncing'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2001')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TendermintRPCApi#syncing_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get a validator set a certain height
    # @param height Block height
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse2002]
    def validatorsets_height_get(height, opts = {})
      data, _status_code, _headers = validatorsets_height_get_with_http_info(height, opts)
      data
    end

    # Get a validator set a certain height
    # @param height Block height
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse2002, Fixnum, Hash)>] InlineResponse2002 data, response status code and response headers
    def validatorsets_height_get_with_http_info(height, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TendermintRPCApi.validatorsets_height_get ...'
      end
      # verify the required parameter 'height' is set
      if @api_client.config.client_side_validation && height.nil?
        fail ArgumentError, "Missing the required parameter 'height' when calling TendermintRPCApi.validatorsets_height_get"
      end
      # resource path
      local_var_path = '/validatorsets/{height}'.sub('{' + 'height' + '}', height.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2002')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TendermintRPCApi#validatorsets_height_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get the latest validator set
    # @param [Hash] opts the optional parameters
    # @return [InlineResponse2002]
    def validatorsets_latest_get(opts = {})
      data, _status_code, _headers = validatorsets_latest_get_with_http_info(opts)
      data
    end

    # Get the latest validator set
    # @param [Hash] opts the optional parameters
    # @return [Array<(InlineResponse2002, Fixnum, Hash)>] InlineResponse2002 data, response status code and response headers
    def validatorsets_latest_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TendermintRPCApi.validatorsets_latest_get ...'
      end
      # resource path
      local_var_path = '/validatorsets/latest'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse2002')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TendermintRPCApi#validatorsets_latest_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
